#!/usr/bin/env node
// Copies css/app.css into js/styles.js so saved client files can embed the
// stylesheet even when Waypoint runs from file:// (where browsers block
// reading linked stylesheets). Run after editing css/app.css:
//   node financial-planner/tools/build-styles.js
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const css = fs.readFileSync(path.join(root, 'css/app.css'), 'utf8');
const out = '/* Generated by tools/build-styles.js from css/app.css. Do not edit. */\n' +
  "(function (root) { (root.FP = root.FP || {}).styles = " + JSON.stringify(css) + "; })(typeof self !== 'undefined' ? self : this);\n";
fs.writeFileSync(path.join(root, 'js/styles.js'), out);
console.log('Wrote js/styles.js (' + Math.round(out.length / 1024) + ' KB)');
